// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdv4r2MtgY5ZuTsxpFtT8fZvM-IBPOf3U',
    appId: '1:978539922884:web:ad696196f597d6eb3f9091',
    messagingSenderId: '978539922884',
    projectId: 'flutterauth-7331f',
    authDomain: 'flutterauth-7331f.firebaseapp.com',
    storageBucket: 'flutterauth-7331f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlJ8luHZ-8IsP9NRYuRMDlRRL_ViWNa4M',
    appId: '1:978539922884:android:2f735da86eca24623f9091',
    messagingSenderId: '978539922884',
    projectId: 'flutterauth-7331f',
    storageBucket: 'flutterauth-7331f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe_ccpY13WI--T26dJfAs7cr2g03pfR6w',
    appId: '1:978539922884:ios:50147177aae546c13f9091',
    messagingSenderId: '978539922884',
    projectId: 'flutterauth-7331f',
    storageBucket: 'flutterauth-7331f.appspot.com',
    iosClientId: '978539922884-5kl21hvc016bikni5cknlc31quevemk3.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAuthentification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBe_ccpY13WI--T26dJfAs7cr2g03pfR6w',
    appId: '1:978539922884:ios:50147177aae546c13f9091',
    messagingSenderId: '978539922884',
    projectId: 'flutterauth-7331f',
    storageBucket: 'flutterauth-7331f.appspot.com',
    iosClientId: '978539922884-5kl21hvc016bikni5cknlc31quevemk3.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAuthentification',
  );
}
